apiVersion: v2
name: saferwall
description: A hackable malware sandbox for the 21st Century
type: application
version: 0.0.1
appVersion: 0.0.1
home: https://www.saferwall.com/
sources:
    - https://github.com/saferwall/saferwall
maintainers:
    - name: Saferwall
      email: admin@saferwall.com
dependencies:
    - name: minio
      version: 4.0.1
      repository: https://kubernetes-charts-incubator.storage.googleapis.com/
      condition: minio.enabled
