########### MINIO ###########
minio:
  # We choose distributed for HA. This can be set to standalone in dev env.
  mode: standalone
  # mode: distributed

  # Number of nodes (applicable only for MinIO distributed mode)
  # Should be a minimum value of 4.
  # replicas: 1

  service:
    type: ClusterIP
    port: 9000

  persistence:
    # Use persistent volume to store data
    enabled: true

    # Size of persistent volume claim
    size: 1Gi

  accessKey: "<accessKey>"
  secretKey: "<secretKey>"

####### COUCHBASE #########
couchbase-cluster:
  enabled: false
  couchbaseCluster:
    create: true
    name: ""
    username: "Administrator"
    password: "password"
    authSecretOverride: ""
    baseImage: "couchbase/server"
    version: "enterprise-6.0.1"
    exposeAdminConsole: true
    adminConsoleServices:
      - data
    exposedFeatures:
      - xdcr
    adminConsoleServiceType: NodePort
    exposedFeatureServiceType: NodePort
    dns:
      domain:
    platform:
    cluster:
      dataServiceMemoryQuota: 256
      indexServiceMemoryQuota: 256
      searchServiceMemoryQuota: 256
      eventingServiceMemoryQuota: 256
      analyticsServiceMemoryQuota: 1024
      indexStorageSetting: memory_optimized
      autoFailoverTimeout: 120
      autoFailoverMaxCount: 3
      autoFailoverOnDataDiskIssues: true
      autoFailoverOnDataDiskIssuesTimePeriod: 120
      autoFailoverServerGroup: false
      logRetentionTime: 604800s
      logRetentionCount: 20
    buckets:
      files:
        name: files
        type: couchbase
        memoryQuota: 128
        replicas: 1
        ioPriority: high
        evictionPolicy: fullEviction
        conflictResolution: seqno
        enableFlush: true
        enableIndexReplica: false
      users:
        name: users
        type: couchbase
        memoryQuota: 128
        replicas: 1
        ioPriority: high
        evictionPolicy: fullEviction
        conflictResolution: seqno
        enableFlush: true
        enableIndexReplica: false

    servers:
      all_services:
        size: 3
        services:
          - data
          - index
          - query
          - search
          - eventing
          - analytics
        serverGroups: []
        pod: {}
    securityContext: {}
    volumeClaimTemplates: []


########### NSQ ###########
nsq:
  nsqd:
    name: nsqd


########### EFS-PROVISONNER ###########
efs-provisioner:
  efsProvisioner:
    efsFileSystemId: "fs-e9a29668"
    awsRegion: "us-east-1"
    provisionerName: "saferwall.com/aws-efs"
    # dnsName: "fs-36d586b7.efs.us-east-1.amazonaws.com"
    # storageClass:
    #   name:  {{ include "saferwall.fullname" . }}-efs

########### BACKEND ###########
backend:
  enabled: true
  name: backend
  replicaCount: 1
  containerPort: 8080
  image:
    repository: saferwall/goavast
    tag: latest
    pullPolicy: Always
  service:
    type: LoadBalancer
    port: 80
    targetPort: 8080

########### FRONTEND ###########
frontend:
  enabled: false
  name: frontend
  replicaCount: 1
  containerPort: 8080
  image:
    repository: saferwall/ui
    tag: latest
    pullPolicy: Always
  service:
    type: LoadBalancer
    port: 80
    targetPort: 8080

########### CONSUMER ###########
consumer:
  enabled: false
  name: consumer
  replicaCount: 1
  image:
    repository: saferwall/consumer
    tag: latest
    pullPolicy: Always
