minio:
  # We choose distributed for HA. This can be set to standalone in dev env. 
  mode: distributed

  # Number of nodes (applicable only for MinIO distributed mode)
  # Should be a minimum value of 4.
  replicas: 4
  
  service:
    type: ClusterIP
    port: 9000

  persistence:
    # Use persistent volume to store data
    enabled: true

    # Size of persistent volume claim	
    size: 1Gi

  accessKey: "12345"
  secretKey: "sjkdhskjfhs" 