########### MINIO ###########
minio:
  # We choose distributed for HA. This can be set to standalone in dev env.
  mode: standalone
  # mode: distributed

  # Number of nodes (applicable only for MinIO distributed mode)
  # Should be a minimum value of 4.
  # replicas: 1

  service:
    type: ClusterIP
    port: 9000

  persistence:
    # Use persistent volume to store data
    enabled: true

    # Size of persistent volume claim
    size: 1Gi

  accessKey: "<accessKey>"
  secretKey: "<secretKey>"

########### EFS-PROVISONNER ###########
efs-provisioner:
  efsProvisioner:
    efsFileSystemId: "fs-da361d5b"
    awsRegion: "us-east-1"
    provisionerName: "saferwall.com/aws-efs"
    # dnsName: "fs-36d586b7.efs.us-east-1.amazonaws.com"
    # storageClass:
    #   name:  {{ include "saferwall.fullname" . }}-efs

########### BACKEND ###########
backend:
  enabled: true
  name: backend
  replicaCount: 1
  containerPort: 8080
  image:
    repository: saferwall/backend
    tag: latest
    pullPolicy: Always
  service:
    type: LoadBalancer
    port: 80
    targetPort: 8080

########### FRONTEND ###########
frontend:
  enabled: false
  name: frontend
  replicaCount: 1
  containerPort: 8080
  image:
    repository: saferwall/ui
    tag: latest
    pullPolicy: Always
  service:
    type: LoadBalancer
    port: 80
    targetPort: 8080

########### CONSUMER ###########
consumer:
  enabled: false
  name: consumer
  replicaCount: 1
  image:
    repository: saferwall/consumer
    tag: latest
    pullPolicy: Always
