apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "saferwall.backend.fullname" . }}
  labels:
    app: {{ include "saferwall.backend.fullname" . }}
data:
  backends_conf: {{ tpl (.Files.Get "files/backend-conf.toml") . | quote }}
