apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "saferwall.consumer.fullname" . }}
  labels:
    app: {{ include "saferwall.consumer.fullname" . }}
data:
  consumer_conf: {{ tpl (.Files.Get "files/consumer-conf.toml") . | quote }}
