{{- if index .Values "cert-manager" "enabled" -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "saferwall.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/client-body-buffer-size: "64M"
    nginx.ingress.kubernetes.io/proxy-body-size: "64M"
spec:
  tls:
  - hosts:
    - {{ .Values.frontendDomainName }}
    - {{ .Values.backendDomainName }}
    - {{ .Values.websiteDomainName }}
    secretName: {{ include "saferwall.fullname" . }}-tls
  rules:
  - host: {{ .Values.frontendDomainName }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "saferwall.frontend.fullname" . }}
          servicePort: {{ .Values.frontend.service.port }}
  - host: {{ .Values.backendDomainName }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "saferwall.backend.fullname" . }}
          servicePort: {{ .Values.backend.service.port }}
  - host: {{ .Values.websiteDomainName }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "saferwall.website.fullname" . }}
          servicePort: {{ .Values.website.service.port }}
{{- end }}