apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "saferwall.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "64M"
    nginx.ingress.kubernetes.io/proxy-body-size: "64M"
    {{- if index .Values "cert-manager" "enabled" -}}
    cert-manager.io/cluster-issuer: letsencrypt-prod
    {{- end }}
spec:
  {{- if index .Values "cert-manager" "enabled" -}}
  tls:
  - hosts:
    - {{ .Values.frontendDomainName }}
    - {{ .Values.backendDomainName }}
    - {{ .Values.websiteDomainName }}
    secretName: {{ include "saferwall.fullname" . }}-tls
  {{- end }}
  rules:
  - host: {{ .Values.global.frontendDomainName }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "saferwall.frontend.fullname" . }}
          servicePort: {{ .Values.frontend.service.port }}
  - host: {{ .Values.global.backendDomainName }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "saferwall.backend.fullname" . }}
          servicePort: {{ .Values.backend.service.port }}
{{- if .Values.website.enabled -}}
  - host: {{ .Values.global.websiteDomainName }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "saferwall.website.fullname" . }}
          servicePort: {{ .Values.website.service.port }}
{{- end }}