 
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "saferwall.fullname" . }}-samples
  annotations:
    volume.beta.kubernetes.io/storage-class: aws-efs
spec:
  {{- if index .Values "efs-provisioner" "enabled" }}
  storageClassName: aws-efs
  {{- else if .Values "nfs-server-provisioner" "enabled" }}
  storageClassName: nfs
  {{- end }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi