# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/saferwall/saferwall
    steps:
      - checkout

      - run:
          name: "Determine which packages need to be built"
          command: |
            chmod +x scripts/commit_check.sh
            ./scripts/commit_check.sh

      - run:
          name: "Install Avast"
          command: |
            if [ -f "/tmp/avast.circleci" ]; then
              cd build/package/multiav/avast
              sudo --preserve-env make install
            fi
  
      - run:
          name: "Install crypo pkg dependencies"
          command: |
            if [ -f "/tmp/crypto.circleci" ]; then
              go get -d github.com/saferwall/saferwall/pkg/crypto
            fi
  
  test:
      docker:
        # specify the version
        - image: circleci/golang:1.11
      working_directory: /go/src/github.com/saferwall/saferwall
      steps:
        - run:
            name: "Running unit tests"
            command: |
              if [ -f "/tmp/avast.circleci" ]; then
                go get -d github.com/saferwall/saferwall/pkg/multiav/avast
                go test -v github.com/saferwall/saferwall/pkg/multiav/avast
              fi

        - run:
            name: "Running unit tests"
            command: |
              if [ -f "/tmp/crypto.circleci" ]; then
                go get -d github.com/saferwall/saferwall/pkg/crypto
                go test -v github.com/saferwall/saferwall/pkg/crypto
              fi

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
  