# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

defaults: &defaults
  docker:
    - image: circleci/golang:1.11
  working_directory: /go/src/github.com/saferwall/saferwall
  
jobs:
  clone_and_hash:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: "Determine which packages need to be built"
          command: |
            chmod +x scripts/commit_check.sh
            ./scripts/commit_check.sh

      - persist_to_workspace:
          root: /tmp/saferwall
          paths:
            - circleci/*

  multiav_avast:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: /tmp/saferwall

      - run:
          name: "Install Avast AV"
          command: |
            sudo --preserve-env sh ./scripts/build_multiav.sh avast

      - run:
          name: "Test Avast go pkg"
          command: |
            sh ./scripts/test_multiav.sh avast

  multiav_avira:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: /tmp/saferwall

      - run:
          name: "Install Avira AV"
          command: |
            sudo --preserve-env sh ./scripts/build_multiav.sh avira

      - run:
          name: "Test Avira go pkg"
          command: |
            sudo sh ./scripts/test_multiav.sh avira

  multiav_bitdefender:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: /tmp/saferwall

      - run:
          name: "Install Bitdefender AV"
          command: |
            sudo --preserve-env sh ./scripts/build_multiav.sh bitdefender

      - run:
          name: "Test Bitdefender go pkg"
          command: |
            sh ./scripts/test_multiav.sh bitdefender
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - clone_and_hash
      - multiav_avast:
          requires:
            - clone_and_hash
      - multiav_avira:
          requires:
            - clone_and_hash
      - multiav_bitdefender:
          requires:
            - clone_and_hash