markdown: kramdown
encoding: utf-8
plugins:
  - jekyll-autoprefixer
  - jekyll-assets

permalink: /blog/:title

assets:
  compress:
    css: true
    js: true

  sources:
    - _assets/stylesheets
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts

  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"

