[backend]
address = ":8800"

[db]
server = "couchbase://172.17.0.2"
username = "username"
password = "password"

[storage]
tmp_samples = "/tmp/samples"
max_file_size = 64000000 # 64MB

[nsq]
addr = "localhost:4150"

[do]
endpoint = "localhost:9000"
seckey = "seckey"
accesskey = "accesskey"
spacename = "samples" 
ssl = false

[auth]
signkey = "signkey"

[smtp]
server = "smtp.example.com"
port = 465
user =  "user@example.com"
password = "password"
identity =  "identity"
sender =  "sender@example.com"
