name: Lint and Test Helm Charts

on:
  pull_request:
    branches: [ master ]

jobs:
  lint-test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup config
        run: cp example.env .env

      - name: Install Minikube
        run: make minikube-install

      - name: Install Kubectl
        run: make kubectl-install

      - name: Setup Minikube
        run: make minikube-up
        
      - name: Install Helm, add repos, and build dependencies
        run: |
            make helm-install \
            && make helm-add-repos \
            && make helm-update-dependency \
            && make helm-init-cert-manager

      - name: Helm Release
        run: make helm-release

      - name: Wait for pods to be ready
        run: kubectl wait --for=condition=Ready pods --all --timeout=360s
