name: Update go MultiAV

on:
  schedule:
  - cron: "0 0 * * *"
  push:

jobs:
  update-clamav:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup config
        run: cp example.env .env

      - name: Build goClamAV docker image
        run: make multiav-build-av-go AV_VENDOR=clamav

  update-avira:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup config
        run: cp example.env .env

      - name: Build goAvira docker image
        run: make multiav-build-av-go AV_VENDOR=avira

  update-comodo:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup config
        run: cp example.env .env

      - name: Build goCOMODO docker image
        run: make multiav-build-av-go AV_VENDOR=comodo

  update-windefender:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup config
        run: cp example.env .env

      - name: Build go Windows Defender docker image
        run: make multiav-build-av-go AV_VENDOR=windefender
