name: Update MultiAV Signature Database

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  update-lamav:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build ClamAV docker image
        run: make multiav-build-av AV_VENDOR=clamav
